import { GenerateResponse } from "@/lib/types";

// Pre-generated mock responses for demo mode.
// Keyed by `${patientId}-${goal}-${tone}` with a fallback default.
// In production, these would be generated by the live API and cached.

const mockData: Record<string, GenerateResponse> = {
  default: {
    provider: "mock",
    generatedAt: new Date().toISOString(),
    channelMessages: [
      {
        channel: "sms",
        variants: [
          {
            id: "sms-a",
            approach: "Empathy-led",
            content:
              "Hi! This is Sarah from your Pomelo Care team. We know things can feel overwhelming right now, and we're here to help. Would you like to schedule a quick check-in this week? Just reply YES and we'll find a time that works for you.",
            engagementLikelihood: "high",
            reasoning:
              "Opens with empathy and acknowledges the patient's emotional state. Uses the care team member's name to build trust. Low-commitment ask (just reply YES) reduces friction. Under 160 characters is not possible for this depth of message, but SMS can support multi-part messages.",
          },
          {
            id: "sms-b",
            approach: "Action-led",
            content:
              "Hi, it's your Pomelo Care team. You have 24/7 access to your nurse care partner — text us anytime with questions about your health. We're here for you!",
            engagementLikelihood: "medium",
            reasoning:
              "Leads with the value proposition (24/7 access). Reminds patient of what's available without being pushy. Shorter and more direct, but less personalized.",
          },
          {
            id: "sms-c",
            approach: "Education-led",
            content:
              "Did you know? Your Pomelo Care benefit includes free virtual visits with nurses and specialists who focus on women's health. No copay, no hassle. Reply LEARN to find out more.",
            engagementLikelihood: "medium",
            reasoning:
              "Leads with a surprising fact to generate curiosity. Emphasizes the no-cost aspect which is compelling for many patients. Clear CTA with simple keyword reply.",
          },
        ],
      },
      {
        channel: "email",
        variants: [
          {
            id: "email-a",
            approach: "Empathy-led",
            subject: "Your care team is thinking of you",
            content:
              "Hi there,\n\nI wanted to reach out personally because we haven't connected in a little while, and I want to make sure you're doing okay.\n\nAs your nurse care partner at Pomelo Care, I'm here to support you — whether that's answering a quick question at midnight or helping you navigate something more complex.\n\nHere's what's available to you right now:\n• 24/7 text and call access to your care team\n• Virtual visits with specialists (no copay)\n• Personalized health resources and guidance\n\nWould you like to schedule a 15-minute check-in this week? I'd love to hear how you're doing.\n\nWarmly,\nSarah Thompson, RN\nYour Pomelo Care Nurse Partner",
            engagementLikelihood: "high",
            reasoning:
              "Personal tone from a named care team member builds trust. Acknowledges the gap without guilt. Lists concrete benefits as reminders of value. Low-pressure ask with specific time commitment (15 min). Warm sign-off reinforces the human connection.",
          },
          {
            id: "email-b",
            approach: "Value-focused",
            subject: "A quick reminder about your Pomelo Care benefits",
            content:
              "Hi there,\n\nJust a friendly reminder that your Pomelo Care benefits are ready whenever you need them. Here's what's included at no cost to you:\n\n• Unlimited text access to your nurse care partner\n• Virtual visits with OB-GYN, mental health, and nutrition specialists\n• 24/7 support for any health questions or concerns\n• Personalized care plans based on your unique needs\n\nMany of our patients tell us that having a nurse they can text anytime — even at 2 AM — makes all the difference.\n\nReady to reconnect? Reply to this email or text us anytime.\n\nYour Pomelo Care Team",
            engagementLikelihood: "medium",
            reasoning:
              "Focuses on concrete benefits and the no-cost aspect. Social proof (\"many of our patients\") builds credibility. Multiple response channels reduce friction. Less personal than variant A but covers more value points.",
          },
        ],
      },
      {
        channel: "in-app",
        variants: [
          {
            id: "inapp-a",
            approach: "Empathy-led",
            content:
              "We've missed you! Your nurse care partner Sarah is here whenever you're ready. Tap to schedule a quick check-in or just say hi.",
            engagementLikelihood: "high",
            reasoning:
              "Short, warm, and personal. Uses the nurse's name. Low-pressure with multiple engagement options. Works well as a push notification or in-app banner.",
          },
          {
            id: "inapp-b",
            approach: "Milestone-based",
            content:
              "You're making great progress on your health journey. Your care team has a personalized update ready for you — tap to view.",
            engagementLikelihood: "medium",
            reasoning:
              "Curiosity-driven approach with a personalized update tease. Positive framing (\"great progress\") even if engagement has dipped. Creates a reason to open the app.",
          },
        ],
      },
    ],
  },
};

// Patient-specific mock overrides for more realistic demos
mockData["keisha-re-engagement-warm-supportive"] = {
  provider: "mock",
  generatedAt: new Date().toISOString(),
  channelMessages: [
    {
      channel: "sms",
      variants: [
        {
          id: "sms-a",
          approach: "Empathy-led",
          content:
            "Hi Keisha, it's Patricia from your Pomelo Care team. I noticed we haven't connected in a few weeks and just wanted to check in. How are you and baby doing? I'm here if you need anything — even just to talk. Reply anytime.",
          engagementLikelihood: "high",
          reasoning:
            "Uses Keisha's name and her specific nurse's name for personal connection. Acknowledges the gap without judgment. Asks about both her and baby, showing holistic concern. At 30 weeks with gestational diabetes, maintaining contact is clinically important. Open-ended invitation reduces pressure.",
        },
        {
          id: "sms-b",
          approach: "Resource-focused",
          content:
            "Keisha, your nurse Patricia wanted you to know: we can help with glucose testing supplies and connect you with food assistance programs. Text us back and we'll get that set up for you.",
          engagementLikelihood: "high",
          reasoning:
            "Directly addresses known barriers (glucose strip costs, food insecurity) that may be contributing to disengagement. Offers concrete, practical help rather than just requesting a check-in. This removes obstacles rather than adding obligations.",
        },
        {
          id: "sms-c",
          approach: "Clinical urgency (gentle)",
          content:
            "Hi Keisha, at 30 weeks your care team wants to make sure you and baby are doing well. Dr. Martinez has some updated guidance for managing your glucose levels. Can we set up a quick 10-min call this week?",
          engagementLikelihood: "medium",
          reasoning:
            "References the clinical specifics (30 weeks, glucose management) to convey importance without being alarmist. Mentions the doctor by name for authority. Specific time ask (10 min) sets expectations. May feel slightly more pressure than variants A/B.",
        },
      ],
    },
    {
      channel: "email",
      variants: [
        {
          id: "email-a",
          approach: "Empathy-led",
          subject: "Checking in on you, Keisha",
          content:
            "Hi Keisha,\n\nIt's Patricia, your nurse care partner at Pomelo Care. I've been thinking about you and wanted to reach out.\n\nI know managing gestational diabetes on top of everything else in life can feel like a lot. You don't have to do this alone — that's exactly what your care team is here for.\n\nA few things I'd love to help with when you're ready:\n\n• Reviewing your glucose levels together and adjusting your plan if needed\n• Connecting you with programs that can help with testing supplies\n• Exploring food assistance options that work for you\n• Scheduling a flexible check-in that fits your schedule\n\nYou can text me anytime at your Pomelo number, or just reply to this email. Even if you just want to vent — I'm here.\n\nTake care of yourself,\nPatricia Hawkins, RN\nYour Pomelo Care Nurse Partner\n\nP.S. If getting to appointments has been a challenge, let me know. We have virtual options and can help figure out transportation.",
            engagementLikelihood: "high",
            reasoning:
              "Deeply personalized to Keisha's specific situation: gestational diabetes management, supply costs, food insecurity, and transportation barriers — all documented in her clinical notes. The P.S. addresses transportation, a known barrier. Tone is warm and non-judgmental, acknowledging the difficulty without making her feel guilty about missed check-ins. Multiple low-friction response options.",
        },
        {
          id: "email-b",
          approach: "Clinical update",
          subject: "Important update from your care team at 30 weeks",
          content:
            "Hi Keisha,\n\nAs you reach 30 weeks, your care team wanted to share some important information about the next phase of your pregnancy.\n\nAt this stage with gestational diabetes, more frequent monitoring helps ensure the best outcomes for you and your baby. Here's what Dr. Martinez recommends:\n\n• Weekly glucose check-ins (can be done via text — just send your numbers)\n• A virtual visit to review your current management plan\n• Connecting with our nutritionist for practical meal planning support\n\nWe've also identified some resources that may help:\n• Glucose testing supply assistance programs\n• Local food support options in your area\n\nYour health and your baby's health are our priority. Let's find a time that works for you — even a 10-minute call can make a big difference.\n\nReply to this email or text us anytime.\n\nYour Pomelo Care Team\nPatricia Hawkins, RN | Dr. Rebecca Martinez, OB-GYN",
            engagementLikelihood: "medium",
            reasoning:
              "Takes a more clinical approach, framing the outreach around medical recommendations rather than emotional connection. References the specific gestational week and condition to convey relevance. Still addresses known barriers (supplies, food) but from a clinical perspective. May work better for patients who respond to authority and medical guidance.",
        },
      ],
    },
    {
      channel: "in-app",
      variants: [
        {
          id: "inapp-a",
          approach: "Empathy-led",
          content:
            "Hi Keisha — your nurse Patricia is checking in. How are you and baby doing? Tap to send her a quick message or schedule a call.",
          engagementLikelihood: "high",
          reasoning:
            "Brief, personal, and warm. Uses the nurse's name to maintain the human connection. Two clear action paths. Works as both a push notification and in-app message.",
        },
        {
          id: "inapp-b",
          approach: "Resource-focused",
          content:
            "Keisha, we found assistance programs for glucose testing supplies near you. Tap to learn more or text your care team.",
          engagementLikelihood: "high",
          reasoning:
            "Leads with a concrete offer of help for a known barrier. This isn't asking Keisha for anything — it's offering something valuable. Practical utility drives engagement.",
        },
      ],
    },
  ],
};

export function getMockResponse(
  patientId: string,
  goal: string,
  tone: string,
  channels: string[]
): GenerateResponse {
  // Try patient-specific mock first
  const specificKey = `${patientId}-${goal}-${tone}`;
  const response = mockData[specificKey] || mockData["default"];

  // Filter to requested channels
  const filtered = {
    ...response,
    generatedAt: new Date().toISOString(),
    channelMessages: response.channelMessages.filter((cm) =>
      channels.includes(cm.channel)
    ),
  };

  return filtered;
}
